project:
  type: website
  output-dir: _site

website:
  title: "vanishingvitamin.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: learnmore.qmd
        text: "Learn more"
    right:
      - href: https://rconnect.usgs.gov/vanishing-vitamin-app/
        target: _blank
        text: App (external)
        icon: box-arrow-up-right
      - icon: github
        href: https://github.com/VanishingVitamin

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

